### ISSUE TITLE
Issues with running examples

### ISSUE THREAD

**Issue by cpsievert** [react-R/reactR#13]
The following examples give me JS console errors (and don't render anything). Happy to provide more context if this isn't already a known issue:

https://github.com/react-R/reactR/blob/master/inst/examples/bizcharts.R
https://github.com/react-R/reactR/blob/master/inst/examples/blueprint.R
https://github.com/react-R/reactR/blob/master/inst/examples/react-sparklines.r
https://github.com/react-R/reactR/blob/master/inst/examples/react-virtualized.R
https://github.com/react-R/reactR/blob/master/inst/examples/semiotic.R
https://github.com/react-R/reactR/blob/master/inst/examples/victory-chart.R

**Comment by timelyportfolio** [comment]
@cpsievert thanks so much for the report, and this is a known issue.  I propose removing most of these now that we have a widget solution.
