### ISSUE TITLE
Multiple Shiny inputs

### ISSUE THREAD

**Issue by stla** [react-R/reactR#46]
Hello,

 I've done a package with multiple Shiny inputs. I'm using `reactShinyInput` multiple times for that, is it a good practice? The `js` file and the `js.map` file generated are suprisingly big.

**Comment by stla** [comment]
Finally I've tried a single `reactShinyInput` with some if-else to select the widget, and this has not changed the sizes of the JS files.

**Comment by timelyportfolio** [comment]
@stla sorry for the very late reply.  I have removed the `mode: develop` from the template which should dramatically reduce the file size.
