### ISSUE TITLE
explore integration with packer

### ISSUE THREAD

**Issue by timelyportfolio** [react-R/reactR#54]
In an effort to enhance the experience for users more accustomed to `R` than `JavaScript`, explore integration with [`packer`](https://github.com/johncoene/packer) from @johncoene.

**Comment by JohnCoene** [comment]
Let me know if I can help!

**Comment by elliothershberg** [comment]
This sounds like a really cool idea! I’ve recently built a package using reactR (thank you for making such a great package). One thing I’ve noticed is that the scaffolding step copies the template `webpack.config.js` and `package.json`. 

This works, but the webpack version that gets installed is webpack v4. I’ve only briefly looked at packer, which looks awesome. It looks like there are functions for detecting outdated NPM packages and also updating them. @JohnCoene could using these help with not relying on the template files that become out of date?

I’d be interested in potentially helping with this integration, this package has been really helpful for me.

**Comment by JohnCoene** [comment]
[packer](https://packer.john-coene.com/#/) is essentially a lot of convenience functions to setup R-projects that use webpack, because I find that webpack comes with quite some overhead.

I think you can always run `npm update` to bump webpack in the project.

**Comment by timelyportfolio** [comment]
@JohnCoene @elliothershberg In the next upgrade, I will make sure that the `webpack` version gets updated in the template.  We lock in a specific version to insure that everything works.  I'll test newest `webpack` to see if any additional changes are required.

I like the idea of using `packer` for the convenience `npm/node` functions that I believe are more understandable for the R user without as much JavaScript experience since they are accessed from the R console instead of terminal.
