### ISSUE TITLE
insure `component` retains `list`

### ISSUE THREAD

**Issue by timelyportfolio** [react-R/reactR#82]
As pointed out in https://github.com/ramnathv/htmlwidgets/issues/477 and https://github.com/glin/reactable/issues/348, `htmlwidgets::JS` will no longer work as expected in `reactR::component`.  I think @glin fix in https://github.com/glin/reactable/commit/1d60ea6d3eaf9a655cf6ebccb973c3b03ae4969d might be the solution that we could make universal if applied in `reactR`.

**Comment by gadenbuie** [comment]
Hi @timelyportfolio, thanks for the fix here and apologies for the disruption. reactR's use of `JS()` was definitely not something I anticipated when working on the PR that changed the recursive behavior of `htmltools::shouldEval()`.

Would you be able to show me in a small example how reactR uses `JS()`? It would help me to understand the scope of the problems this new behavior is causing.

**Comment by timelyportfolio** [comment]
@gadenbuie thanks so much for working through this.  Happy to schedule a time to discuss if that works best.  My best summary of how `reactR` uses `JS()` is that a `reactR::component` is a thin wrapper of `shiny.tag` and any `reactR` widget is nearly identical to an `htmlwidget` except there might be `component` instead of `shiny.tag`.

**Comment by glin** [comment]
@gadenbuie @timelyportfolio Thanks for fixes both in htmlwidgets and reactR. I don't see any downsides to leaving the workaround in either, especially because there are likely still users on htmlwidgets 1.6.3 out there, and it's kind of a hard issue to spot. I will probably leave in the workaround for reactable a little longer as well.

**Comment by timelyportfolio** [comment]
thanks @glin and @gadenbuie I'll plan to leave the patch to add `list` to set of classes for `reactR::component`.
