### ISSUE TITLE
Question: wrapper around react flow

### ISSUE THREAD

**Issue by DavZim** [react-R/reactR#93]
Hi all,
first of all, thank you for the wonderful package, I enjoy using it indirectly almost every day and now I want to use it directly to "import" a react component to R and shiny.

I am following the [htmlwidgets intro](https://react-r.github.io/reactR/articles/intro_htmlwidgets.html) to create a basic wrapper for [`@xyflow/react`](https://github.com/xyflow/xyflow/tree/main/packages/react#quickstart).

I think I followed all steps, but my JS knowledge is growing (to avoid the term limited :)). But in the end the app does not show anything.
Is this the right place to ask for help? Or do you have some other platform where we can discuss something like this?

The minimal ~working~ example can be found here: https://github.com/DavZim/reactflow/.

The package builds successfully, but when I run the shiny app, I get the following error in the JS/developer console and no output is shown:

```
Uncaught TypeError: o is undefined
    <anonymous> React
    Webpack 7
react-jsx-runtime.production.min.js:10:133
```

Any hint is appreciated as I want to learn more about reactR and its possibilities.

## Files

As a quick reference, I thought it might be helpful to pull in the most important files:

[`R/reactflow.R`](https://github.com/DavZim/reactflow/blob/master/R/reactflow.R)

```R
#' @export
reactflow <- function(nodes, edges, ..., width = NULL, height = NULL, elementId = NULL) {
  # describe a React component to send to the browser for rendering.
  
  component <- reactR::component(
    "Reactflow",
    list(nodes = nodes, edges = edges, ...)
  )

  # create widget
  htmlwidgets::createWidget(
    name = 'reactflow',
    reactR::reactMarkup(component),
    width = width,
    height = height,
    package = 'reactflow',
    elementId = elementId
  )
}

#' @export
miniMap <- function(...) {
  reactR::React$MiniMap(...)
}

#' @export
controls <- function(...) {
  reactR::React$Controls(...)
}
#' @export
background <- function(...) {
  reactR::React$Background(...)
}
```

[`srcjs/reactflow.jsx`](https://github.com/DavZim/reactflow/blob/master/srcjs/reactflow.jsx)
```js
import { ReactFlow, MiniMap, Controls, Background } from '@xyflow/react';
import '@xyflow/react/dist/style.css';

import { reactWidget } from 'reactR';

reactWidget('reactflow', 'output', {
  ReactFlow: ReactFlow,
  MiniMap: MiniMap,
  Controls: Controls,
  Background: Background
});
```

and then I use the element in [`app.R`](https://github.com/DavZim/reactflow/blob/master/app.R)
```r
output$widgetOutput <- renderReactflow({
    nodes <- list(
      list(id = "1", position = list(x = 0, y = 0), data = list(label = "1")),
      list(id = "2", position = list(x = 0, y = 100), data = list(label = "2"))
    )
    edges <- list(
      list(id = "e1-2", source = "1", target = "2")
    )
    reactflow(
      nodes = nodes,
      edges = edges,

      miniMap(), 
      controls(), 
      background()
    )
  })
```

And this is what the official doc shows as a [quickstart](https://github.com/xyflow/xyflow/tree/main/packages/react#quickstart):
```js
import { useCallback } from 'react';
import {
  ReactFlow,
  MiniMap,
  Controls,
  Background,
  useNodesState,
  useEdgesState,
  addEdge,
} from '@xyflow/react';

import '@xyflow/react/dist/style.css';

const initialNodes = [
  { id: '1', position: { x: 0, y: 0 }, data: { label: '1' } },
  { id: '2', position: { x: 0, y: 100 }, data: { label: '2' } },
];

const initialEdges = [{ id: 'e1-2', source: '1', target: '2' }];

function Flow() {
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);

  const onConnect = useCallback((params) => setEdges((eds) => addEdge(params, eds)), [setEdges]);

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      onConnect={onConnect}
    >
      <MiniMap />
      <Controls />
      <Background />
    </ReactFlow>
  );
}

export default Flow;
```

**Comment by timelyportfolio** [comment]
@DavZim good a place as any.  Thanks for trying it out.  I'll look over the weekend.

**Comment by timelyportfolio** [comment]
So close, I think https://github.com/DavZim/reactflow/pull/1 should fix it.
